= Concurrency in context of the JVM

Concurrency: Suppose what you have with you is a limited set of resources and there are more than that number, contenders for those valuables, competing with each other to gain access to them. So the way you want these contenders to access the resource, and the way you solve this is a concurrency problem.

Structured concurrency: Suppose you are executing a task, and you need to complete some concurrent tasks that fork from this onto some other threads. If you are required to wait for them to complete and join back to you, what you get is structured concurrency. You must wait for them to complete. The set of threads that have been spawned basically can be grouped together, classified together.

Unstructured concurrency: But suppose instead of waiting for those tasks to join back, your requirement just asks for you to exit after spawning, so that you don't wait for them to complete, what you get is called un-structured concurrency. Basically submit that job in the background to complete, meanwhile you exit and relax.

Your operating system can only support thousands of threads due to various factors, but the socket connections supported can be in millions. Therefore, the number of concurrent tasks or users that you can entertain (in case of a server) is limited.

Parallelism: Contrary to the concurrency, I believe the parallelism is where you have that abundance of resources and what you want is that this one task be completed in an optimal way that takes advantage of these resources wisely, at once, in parallel. You split that task into parallel-ly executable tasks.